**Introduction to NumPy**

NumPy (short form for Numerical Python) is the most fundamental package designed for scientific computing and data analysis. Most of the other packages such as pandas, statsmodels are built on top of it, and is an important package to know and learn about. At the heart of NumPy is a data structure called **ndarray**. ndarray is a basically a multi-dimensional array that is built specifically for the purpose of numerical data analysis. Python also has array capabilities, but they are more generic. The advantage of using ndarray is that processing is extremely efficient and fast. 

You can perform standard mathematical operations on either individual elements or complete array. The range of functions covered is linear algebra, statistical operations, and other specialized mathematical operations. For our purpose, we need to know about ndarray and the range of mathematical functions that are relevant to our research purpose. If you already know languages such as C, Fortran, then you can integrate NumPy code with code written in these languages and can pass NumPy arrays seamlessly. 

From an overall perspective, understanding of NumPy will help us in using pandas effectively as it is built on top of NumPy and frequently we will also be using functions of NumPy in research work. In the current session, we will only look at some of the most important features of NumPy. For a full listing of NumPy features, please visit http://wiki.scipy.org/Numpy_Example_List .

Possible application of NumPy package in research work are:

+ Algorithmic operations such as sorting, grouping and set operations
+ Performing repetitive operations on whole arrays of data without using loops
+ Data merging and alignment operations
+ Data indexing, filtering, and transformation on individual elements or whole arrays
+ Data summarization and descriptive statistics

**Installing NumPy**

In order to check if NumPy is installed, go to Package Manager and type NumPy. You will get a list of packages with names closely matching to NumPy. For our purpose, we need to focus on package named numpy 1.xx. If the package is not installed, click on Install. 

**Importing NumPy**

In order to be able to use NumPy, first import it using import statement

In [1]:
import numpy as np

The above statement will import all of NumPy into your workspace. For starters its good, but if you are doing performance intensive work, then saving space is of importance. In such cases, you can import specific modules of NumPy by using

In [2]:
from numpy import array

ndarray
The most important data structure in NumPy is an n-dimensional array object. Using ndarray, you can store large multidimensional datasets in Python. Being an array, you can perform mathematical operations on these arrays either one element at a time or on complete arrays without using loops. The way to initialize an array object is

In [4]:
a = array((1,2,3,4,5))    #initializes an array a and assigns values to it
b = array((10,20,30,40,50)) # initializes another array b
print(a)
print(b)
print(a+b) 
print(a+5) 
print(a**2) 

[1 2 3 4 5]
[10 20 30 40 50]
[11 22 33 44 55]
[ 6  7  8  9 10]
[ 1  4  9 16 25]


In [18]:
c = array(np.arange(15))   #arange function here works as a sequence or counter
anarray = array(np.arange(1,15,2)) 
onemorearray = array(np.linspace(1,10,15)) 
print(c)
print(anarray)
print(onemorearray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  3  5  7  9 11 13]
[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]


With each ndarray are associated two attributes: shape of the array, and type of the array. The shape of the array tells you about dimensionality of the array (rows and columns), and type of the array tells you about the data type contained in the array.

In [22]:
data = np.array((32,45,123,'test',23,2123))
print(data.shape)
print(data.dtype)
print(data.size)

(6,)
<U11
6


In [21]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2
arr2.shape

(2, 4)

In [11]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(30)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((5,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
np.eye(5) # creates a 5*5 identity matrix. 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.diag(array([1,3,5,3,4,5]))

array([[1, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

**pandas**

pandas is the primary package for performing data analysis tasks in Python. pandas derives its name from panel data analysis and is the fundamental package that provides relational data structures (think Excel, SQL type) and a host of capabilities to play with those data structures. It is the most widely used package in Python for data analysis tasks, and is very good to work with cross sectional, time series, and panel data analysis. Python sits on top of NumPy and can be used with NumPy arrays and the functions in NumPy. How is pandas suited for a researcher’s needs:

+ Has a tabular data structure that can hold both homogenous and heterogenous data.
+ Very good indexing capabilities that makes data alignment and merging easy.
+ Good time series functionality. No need to use different data structures for time series and cross sectional data. Allows for both ordered and unordered time-series data.
+ A host of statistical functions developed around NumPy and pandas that makes a researcher’s task easy and fast.
+ Programming is lot simpler and faster.
+ Easily handles data manipulation and cleaning.
+ Easy to expand and shorten data sets. Comprehensive merging, joins, and group by functionality to join multiple data sets.

**Installing pandas** 

In order to check if pandas is installed, go to Package Manager and type pandas. By default, pandas already comes installed with a distribution of Canopy. If the package is not installed, click on Install.

**Importing pandas**

In order to be able to use NumPy, first import it using import statement


In [23]:
import pandas as pd #this will import pandas into your workspace

In [24]:
import numpy as np  #we will be using numpy functions so import numpy

**Data Structures in pandas**

There are two basic data structures in pandas: Series and DataFrame

**Series:** It is similar to a NumPy 1-dimensional array. In addition to the values that are specified by the programmer, pandas attaches a label to each of the values. If the labels are not provided by the programmer, then pandas assigns labels ( 0 for first element, 1 for second element and so on). A benefit of assigning labels to data values is that it becomes easier to perform manipulations on the dataset as the whole dataset becomes more of a dictionary where each value is associated with a label. 


In [25]:
series1 = pd.Series([10,20,30,40])
series1

0    10
1    20
2    30
3    40
dtype: int64

In [26]:
series1.values

array([10, 20, 30, 40], dtype=int64)

In [27]:
series1.index

RangeIndex(start=0, stop=4, step=1)

If you want to specify custom index values rather than the default ones provided, you can do so using the following command

In [28]:
series2 = pd.Series([10,20,30,40,50], index=['one','two','three','four','five'])
series2

one      10
two      20
three    30
four     40
five     50
dtype: int64

The ways of accesing elements in a Series object are similar to what we have seen in NumPy, and you can perform NumPy operations on Series data arrays.

In [29]:
series2[2]

30

In [30]:
series2['three']

30

In [31]:
series2[['one', 'three', 'five']]

one      10
three    30
five     50
dtype: int64

In [32]:
series2[[0,1,3]]

one     10
two     20
four    40
dtype: int64

In [33]:
series2 + 4

one      14
two      24
three    34
four     44
five     54
dtype: int64

In [34]:
series2 ** 3

one        1000
two        8000
three     27000
four      64000
five     125000
dtype: int64

In [35]:
series2[series2>30]

four    40
five    50
dtype: int64

In [36]:
np.sqrt(series2)

one      3.162278
two      4.472136
three    5.477226
four     6.324555
five     7.071068
dtype: float64

If you have a dictionary, you can create a Series data structure from that dictionary. Suppose you are interested in EPS values for firms and the values come from different sources and is not clean. In that case you dont have to worry about cleaning and aligning those values. 

In [37]:
years = [90, 91, 92, 93, 94, 95]
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm1 = pd.Series(f1,index=years)
firm1

90     8
91     9
92     7
93     8
94     9
95    11
dtype: int64

In [38]:
f2 = {90:14,92:9, 93:13, 94:5}
firm2 = pd.Series(f2,index=years)
firm2

90    14.0
91     NaN
92     9.0
93    13.0
94     5.0
95     NaN
dtype: float64

In [39]:
f3 = {93:10, 94:12, 95: 13}
firm3 = pd.Series(f3,index=years)
firm3

90     NaN
91     NaN
92     NaN
93    10.0
94    12.0
95    13.0
dtype: float64

NaN stands for missing or NA values in pandas. Make use of isnull() function to find out if there are any missing values in the data structure.

In [40]:
pd.isnull(firm3)

90     True
91     True
92     True
93    False
94    False
95    False
dtype: bool

A key feature of Series data is structures is that you don't have to worry about data alignment. For example, if we have run a word count program on two different files and we have the following data structures

In [41]:
dict1 = {'finance': 10, 'earning': 5, 'debt':8}
dict2 = {'finance' : 8, 'compensation':4, 'earning': 9}
count1 = pd.Series(dict1)
count2 = pd.Series(dict2)
print(count1)
count2

finance    10
earning     5
debt        8
dtype: int64


finance         8
compensation    4
earning         9
dtype: int64

If we want to calculate the sum of common words in combined files, then we dont have to worry about data alignment. If we want to include all words, then we can take care of NaN values and compute the sum. By default, Series data structure ignores NaN values. NaN values stand for missing data values.

In [42]:
count1+count2

compensation     NaN
debt             NaN
earning         14.0
finance         18.0
dtype: float64

**Data Frame**

DataFrame is a tabular data structure in which data is laid out in rows and column format (similar to a CSV and SQL file), but it can also be used for higher dimensional data sets. The DataFrame object can contain homogenous and heterogenous values, and can be thought of as a logical extension of Series data structures. In contrast to Series, where there is one index, a DataFrame object has one index for column and one index for rows. This allows flexibility in accessing and manipulating data.

In [43]:
data = pd.DataFrame({'price':[95, 25, 85, 41, 78],
                     'ticker':['AXP', 'CSCO', 'DIS', 'MSFT', 'WMT'],
                     'company':['American Express', 'Cisco', 'Walt Disney','Microsoft', 'Walmart']})
data

price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco
2     85    DIS       Walt Disney
3     41   MSFT         Microsoft
4     78    WMT           Walmart

If a column is passed with no values, it will simply have NaN values

In order to access a column, simply mention the column name

In [44]:
data['company']

0    American Express
1               Cisco
2         Walt Disney
3           Microsoft
4             Walmart
Name: company, dtype: object

In [45]:
data.company

0    American Express
1               Cisco
2         Walt Disney
3           Microsoft
4             Walmart
Name: company, dtype: object

In [47]:
data.iloc[2]

price               85
ticker             DIS
company    Walt Disney
Name: 2, dtype: object

In [50]:
data.loc[data.ticker=='DIS']

price ticker      company
2     85    DIS  Walt Disney

In order to add additional columns

In [51]:
data['Year'] = 2014
data

price ticker           company  Year
0     95    AXP  American Express  2014
1     25   CSCO             Cisco  2014
2     85    DIS       Walt Disney  2014
3     41   MSFT         Microsoft  2014
4     78    WMT           Walmart  2014

In [52]:
data['pricesquared'] = data.price**2
data

price ticker           company  Year  pricesquared
0     95    AXP  American Express  2014          9025
1     25   CSCO             Cisco  2014           625
2     85    DIS       Walt Disney  2014          7225
3     41   MSFT         Microsoft  2014          1681
4     78    WMT           Walmart  2014          6084

In [53]:
del data['pricesquared']
data

price ticker           company  Year
0     95    AXP  American Express  2014
1     25   CSCO             Cisco  2014
2     85    DIS       Walt Disney  2014
3     41   MSFT         Microsoft  2014
4     78    WMT           Walmart  2014

In [55]:
data['pricesquared'] = 'NaN'
data

price ticker           company  Year pricesquared
0     95    AXP  American Express  2014          NaN
1     25   CSCO             Cisco  2014          NaN
2     85    DIS       Walt Disney  2014          NaN
3     41   MSFT         Microsoft  2014          NaN
4     78    WMT           Walmart  2014          NaN

In [57]:
data['sequence'] = np.arange(1,6)
data

price ticker           company  Year pricesquared  sequence
0     95    AXP  American Express  2014          NaN         1
1     25   CSCO             Cisco  2014          NaN         2
2     85    DIS       Walt Disney  2014          NaN         3
3     41   MSFT         Microsoft  2014          NaN         4
4     78    WMT           Walmart  2014          NaN         5

In [58]:
data.values

array([[95, 'AXP', 'American Express', 2014, 'NaN', 1],
       [25, 'CSCO', 'Cisco', 2014, 'NaN', 2],
       [85, 'DIS', 'Walt Disney', 2014, 'NaN', 3],
       [41, 'MSFT', 'Microsoft', 2014, 'NaN', 4],
       [78, 'WMT', 'Walmart', 2014, 'NaN', 5]], dtype=object)

In [59]:
newdata = data.drop(2)

In [60]:
newdata

price ticker           company  Year pricesquared  sequence
0     95    AXP  American Express  2014          NaN         1
1     25   CSCO             Cisco  2014          NaN         2
3     41   MSFT         Microsoft  2014          NaN         4
4     78    WMT           Walmart  2014          NaN         5

In [61]:
years = [90, 91, 92, 93, 94, 95]
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm1 = pd.Series(f1,index=years)
firm1
f2 = {90:14,92:9, 93:13, 94:5}
firm2 = pd.Series(f2,index=years)
firm2
f3 = {93:10, 94:12, 95: 13}
firm3 = pd.Series(f3,index=years)
firm3
df1 = pd.DataFrame(columns=['Firm1','Firm2','Firm3'],index=years)
df1
df1.Firm1 = firm1
df1.Firm2 = firm2
df1.Firm3 = firm3
df1

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [64]:
dft = df1.T
dft
del dft[90]
dft

91   92    93    94    95
Firm1  9.0  7.0   8.0   9.0  11.0
Firm2  NaN  9.0  13.0   5.0   NaN
Firm3  NaN  NaN  10.0  12.0  13.0

You can pass a number of data structures to DataFrame such as a ndarray, lists, dict, Series, and another DataFrame. You can also reindex to confirm to data to a new index. Reindexing is a powerful feature that allows you to access data in a number of different ways, and also to confirm data to some new time series or other index.

In [65]:
reindexdf1 = df1.reindex([88,89,90,91,92,93,94,95,96,97,98])
reindexdf1

Firm1  Firm2  Firm3
88    NaN    NaN    NaN
89    NaN    NaN    NaN
90    8.0   14.0    NaN
91    9.0    NaN    NaN
92    7.0    9.0    NaN
93    8.0   13.0   10.0
94    9.0    5.0   12.0
95   11.0    NaN   13.0
96    NaN    NaN    NaN
97    NaN    NaN    NaN
98    NaN    NaN    NaN

In [67]:
reindexdf1 = df1.reindex(np.arange(1988,2008))
reindexdf1

Firm1  Firm2  Firm3
1988    NaN    NaN    NaN
1989    NaN    NaN    NaN
1990    NaN    NaN    NaN
1991    NaN    NaN    NaN
1992    NaN    NaN    NaN
1993    NaN    NaN    NaN
1994    NaN    NaN    NaN
1995    NaN    NaN    NaN
1996    NaN    NaN    NaN
1997    NaN    NaN    NaN
1998    NaN    NaN    NaN
1999    NaN    NaN    NaN
2000    NaN    NaN    NaN
2001    NaN    NaN    NaN
2002    NaN    NaN    NaN
2003    NaN    NaN    NaN
2004    NaN    NaN    NaN
2005    NaN    NaN    NaN
2006    NaN    NaN    NaN
2007    NaN    NaN    NaN

In [68]:
years1 = [90, 91, 92, 93, 94, 95]
f4 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm4 = pd.Series(f4,index=years)
f5 = {90:14,91:12, 92:9, 93:13, 94:5, 95:8}
firm5 = pd.Series(f5,index=years)
f6 = {90:8, 91: 9, 92:9,93:10, 94:12, 95: 13}
firm6 = pd.Series(f6,index=years)
df2 = pd.DataFrame(columns=['Firm1','Firm2','Firm3'],index=years1)
df2.Firm1 = firm4
df2.Firm2 = firm5
df2.Firm3 = firm6
df2

Firm1  Firm2  Firm3
90      8     14      8
91      9     12      9
92      7      9      9
93      8     13     10
94      9      5     12
95     11      8     13

In [69]:
reindexdf2 = df2.reindex([88,89,90,91,92,93,94,95,96,97,98], fill_value=0)
reindexdf2

Firm1  Firm2  Firm3
88      0      0      0
89      0      0      0
90      8     14      8
91      9     12      9
92      7      9      9
93      8     13     10
94      9      5     12
95     11      8     13
96      0      0      0
97      0      0      0
98      0      0      0

Similarly, you have backfill (bfill) method to fill values backwards.

In [70]:
df2

Firm1  Firm2  Firm3
90      8     14      8
91      9     12      9
92      7      9      9
93      8     13     10
94      9      5     12
95     11      8     13

In [71]:
reindexdf3 = df2.reindex([88,89,90,91,92,93,94,95,96,97,98], method='ffill')
reindexdf3

Firm1  Firm2  Firm3
88    NaN    NaN    NaN
89    NaN    NaN    NaN
90    8.0   14.0    8.0
91    9.0   12.0    9.0
92    7.0    9.0    9.0
93    8.0   13.0   10.0
94    9.0    5.0   12.0
95   11.0    8.0   13.0
96   11.0    8.0   13.0
97   11.0    8.0   13.0
98   11.0    8.0   13.0

In [72]:
reindexdf1

Firm1  Firm2  Firm3
1988    NaN    NaN    NaN
1989    NaN    NaN    NaN
1990    NaN    NaN    NaN
1991    NaN    NaN    NaN
1992    NaN    NaN    NaN
1993    NaN    NaN    NaN
1994    NaN    NaN    NaN
1995    NaN    NaN    NaN
1996    NaN    NaN    NaN
1997    NaN    NaN    NaN
1998    NaN    NaN    NaN
1999    NaN    NaN    NaN
2000    NaN    NaN    NaN
2001    NaN    NaN    NaN
2002    NaN    NaN    NaN
2003    NaN    NaN    NaN
2004    NaN    NaN    NaN
2005    NaN    NaN    NaN
2006    NaN    NaN    NaN
2007    NaN    NaN    NaN

In [73]:
reindexdf3

Firm1  Firm2  Firm3
88    NaN    NaN    NaN
89    NaN    NaN    NaN
90    8.0   14.0    8.0
91    9.0   12.0    9.0
92    7.0    9.0    9.0
93    8.0   13.0   10.0
94    9.0    5.0   12.0
95   11.0    8.0   13.0
96   11.0    8.0   13.0
97   11.0    8.0   13.0
98   11.0    8.0   13.0

In [74]:
reindexdf1+reindexdf3

Firm1  Firm2  Firm3
88      NaN    NaN    NaN
89      NaN    NaN    NaN
90      NaN    NaN    NaN
91      NaN    NaN    NaN
92      NaN    NaN    NaN
93      NaN    NaN    NaN
94      NaN    NaN    NaN
95      NaN    NaN    NaN
96      NaN    NaN    NaN
97      NaN    NaN    NaN
98      NaN    NaN    NaN
1988    NaN    NaN    NaN
1989    NaN    NaN    NaN
1990    NaN    NaN    NaN
1991    NaN    NaN    NaN
1992    NaN    NaN    NaN
1993    NaN    NaN    NaN
1994    NaN    NaN    NaN
1995    NaN    NaN    NaN
1996    NaN    NaN    NaN
1997    NaN    NaN    NaN
1998    NaN    NaN    NaN
1999    NaN    NaN    NaN
2000    NaN    NaN    NaN
2001    NaN    NaN    NaN
2002    NaN    NaN    NaN
2003    NaN    NaN    NaN
2004    NaN    NaN    NaN
2005    NaN    NaN    NaN
2006    NaN    NaN    NaN
2007    NaN    NaN    NaN

In [75]:
reindexdf1.add(reindexdf3, fill_value=0)

Firm1  Firm2  Firm3
88      NaN    NaN    NaN
89      NaN    NaN    NaN
90      8.0   14.0    8.0
91      9.0   12.0    9.0
92      7.0    9.0    9.0
93      8.0   13.0   10.0
94      9.0    5.0   12.0
95     11.0    8.0   13.0
96     11.0    8.0   13.0
97     11.0    8.0   13.0
98     11.0    8.0   13.0
1988    NaN    NaN    NaN
1989    NaN    NaN    NaN
1990    NaN    NaN    NaN
1991    NaN    NaN    NaN
1992    NaN    NaN    NaN
1993    NaN    NaN    NaN
1994    NaN    NaN    NaN
1995    NaN    NaN    NaN
1996    NaN    NaN    NaN
1997    NaN    NaN    NaN
1998    NaN    NaN    NaN
1999    NaN    NaN    NaN
2000    NaN    NaN    NaN
2001    NaN    NaN    NaN
2002    NaN    NaN    NaN
2003    NaN    NaN    NaN
2004    NaN    NaN    NaN
2005    NaN    NaN    NaN
2006    NaN    NaN    NaN
2007    NaN    NaN    NaN

You can use NumPy functions inside DataFrame objects.

In [76]:
dataframe = pd.DataFrame(np.random.randn(3,3),columns=['one','two','three'])
dataframe

one       two     three
0 -0.014071 -0.232067 -0.699151
1 -0.367758 -0.330762  0.080723
2 -0.321115  0.429986  1.749682

In [77]:
np.abs(dataframe)

one       two     three
0  0.014071  0.232067  0.699151
1  0.367758  0.330762  0.080723
2  0.321115  0.429986  1.749682

In [78]:
f = lambda x:x.max()-x.min()
dataframe.apply(f)

one      0.353687
two      0.760748
three    2.448833
dtype: float64

In [79]:
dataframe.apply(f,axis=1)

0    0.685080
1    0.448481
2    2.070798
dtype: float64

In [81]:
g = lambda x: x - np.mean(x)
dataframe.apply(g)

one       two     three
0  0.220244 -0.187786 -1.076236
1 -0.133443 -0.286481 -0.296362
2 -0.086800  0.474267  1.372598

In [83]:
def f(x):
    return pd.Series([np.mean(x), x.max(), x.min()], index=['mean','max','min'])
dataframe.apply(f,axis=1)

mean       max       min
0 -0.315097 -0.014071 -0.699151
1 -0.205932  0.080723 -0.367758
2  0.619518  1.749682 -0.321115

In [84]:
dataframe = pd.DataFrame(np.random.randn(3,3),columns=['one','two','three'])
dataframe

one       two     three
0  0.868210 -0.406960  2.472641
1 -0.242521 -1.743720  0.568430
2 -0.070392 -1.205008  0.179005

In [86]:
dataframe.sort_values(by='one')

one       two     three
1 -0.242521 -1.743720  0.568430
2 -0.070392 -1.205008  0.179005
0  0.868210 -0.406960  2.472641

In [88]:
dataframe.sort_values(by=['one','two'])

one       two     three
1 -0.242521 -1.743720  0.568430
2 -0.070392 -1.205008  0.179005
0  0.868210 -0.406960  2.472641

In [89]:
dataframe.sum()

one      0.555296
two     -3.355688
three    3.220075
dtype: float64

In [90]:
dataframe.sum(axis=1)

0    2.933891
1   -1.417811
2   -1.096396
dtype: float64

In [91]:
dataframe.cumsum(axis=1)

one       two     three
0  0.868210  0.461250  2.933891
1 -0.242521 -1.986241 -1.417811
2 -0.070392 -1.275401 -1.096396

In [92]:
dataframe.describe()

one       two     three
count  3.000000  3.000000  3.000000
mean   0.185099 -1.118563  1.073358
std    0.597819  0.672559  1.227357
min   -0.242521 -1.743720  0.179005
25%   -0.156457 -1.474364  0.373717
50%   -0.070392 -1.205008  0.568430
75%    0.398909 -0.805984  1.520535
max    0.868210 -0.406960  2.472641

If you have non-numeric data, then applying describe function would produce statistics such as count, unique, frequency. In addition to this, you can also calculate skewness (skew), kurtosis (kurt), percent changes, difference, and other statistics.

**Missing Data**

pandas have a number of features to deal with missing data. We have seen an example of the case of descriptive statistics, where missing values are not taken into account while calculating the descriptive statistics. Missing data is denoted by NaN. 

In [93]:
years = [90, 91, 92, 93, 94, 95]
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm1 = pd.Series(f1,index=years)
firm1
f2 = {90:14,92:9, 93:13, 94:5}
firm2 = pd.Series(f2,index=years)
firm2
f3 = {93:10, 94:12, 95: 13}
firm3 = pd.Series(f3,index=years)
firm3
df3 = pd.DataFrame(columns=['Firm1','Firm2','Firm3'],index=years)
df3
df3.Firm1 = firm1
df3.Firm2 = firm2
df3.Firm3 = firm3
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [94]:
firm2

90    14.0
91     NaN
92     9.0
93    13.0
94     5.0
95     NaN
dtype: float64

In [95]:
nadeleted = firm2.dropna()
nadeleted

90    14.0
92     9.0
93    13.0
94     5.0
dtype: float64

In [96]:
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In case of DataFrame, if you use dropna, it deletes entire row by default. Another way is to drop only those rows that are all NA. If you want to drop columns, pass axis=1

In [103]:
cleandf3 = df3.dropna()

In [104]:
cleandf3

Firm1  Firm2  Firm3
93      8   13.0   10.0
94      9    5.0   12.0

In [105]:
clean2 = df3.dropna(how='all')
clean2

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [106]:
columndrop = df3.dropna(axis=1)
columndrop

Firm1
90      8
91      9
92      7
93      8
94      9
95     11

In [107]:
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [108]:
thresholddf = df3.dropna(thresh=2)
thresholddf

Firm1  Firm2  Firm3
90      8   14.0    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [109]:
fillna1 = df3.fillna(0)
fillna1

Firm1  Firm2  Firm3
90      8   14.0    0.0
91      9    0.0    0.0
92      7    9.0    0.0
93      8   13.0   10.0
94      9    5.0   12.0
95     11    0.0   13.0

In [110]:
fillna2 = df3.fillna({'Firm1':8, 'Firm2': 10, 'Firm3':14})
fillna2

Firm1  Firm2  Firm3
90      8   14.0   14.0
91      9   10.0   14.0
92      7    9.0   14.0
93      8   13.0   10.0
94      9    5.0   12.0
95     11   10.0   13.0

In [111]:
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [112]:
fillna3 = df3.fillna(method='ffill')
fillna3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9   14.0    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    5.0   13.0

In [113]:
fillna4 = df3.fillna(method='bfill',limit=2)
fillna4

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    9.0   10.0
92      7    9.0   10.0
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [114]:
fillna5 = df3.fillna(df3.mean())
fillna5

Firm1  Firm2      Firm3
90      8  14.00  11.666667
91      9  10.25  11.666667
92      7   9.00  11.666667
93      8  13.00  10.000000
94      9   5.00  12.000000
95     11  10.25  13.000000

**Hierarchical Indexing**

Hierarchical indexing allows you to have index on an index (multiple index). It is an important feature of pandas using which you can select subsets of data and perform independent analyses on them. For example, suppose you have firm prices data and the data is indexed by firm name. On top of that, you can index firms by industry. Thus, industry becomes an index on top of firms. You can then perform analyses either on individual firm, or on group of firms in an industry, or on the whole dataset.

In [115]:
h_i_data = pd.Series(np.random.randn(10),index=[['Ind1','Ind1','Ind1','Ind1','Ind2','Ind2','Ind2','Ind3','Ind3','Ind3'],
                                              [1,2,3,4,1,2,3,1,2,3]])
h_i_data

Ind1  1    0.311001
      2   -0.117696
      3    0.682512
      4   -0.858294
Ind2  1   -0.400267
      2   -0.616860
      3   -0.685990
Ind3  1    0.027995
      2    0.337804
      3   -0.617471
dtype: float64

In [116]:
h_i_data['Ind3']

1    0.027995
2    0.337804
3   -0.617471
dtype: float64

In [117]:
h_i_data['Ind1':'Ind3']

Ind1  1    0.311001
      2   -0.117696
      3    0.682512
      4   -0.858294
Ind2  1   -0.400267
      2   -0.616860
      3   -0.685990
Ind3  1    0.027995
      2    0.337804
      3   -0.617471
dtype: float64

In [118]:
h_i_data[['Ind1','Ind3']]

Ind1  1    0.311001
      2   -0.117696
      3    0.682512
      4   -0.858294
Ind3  1    0.027995
      2    0.337804
      3   -0.617471
dtype: float64

In [119]:
h_i_data[:,3]

Ind1    0.682512
Ind2   -0.685990
Ind3   -0.617471
dtype: float64

In [121]:
h_i_data[:,4]

Ind1   -0.858294
dtype: float64

In [122]:
h_i_data.unstack()

1         2         3         4
Ind1  0.311001 -0.117696  0.682512 -0.858294
Ind2 -0.400267 -0.616860 -0.685990       NaN
Ind3  0.027995  0.337804 -0.617471       NaN

In [123]:
h_i_data.unstack().stack()

Ind1  1    0.311001
      2   -0.117696
      3    0.682512
      4   -0.858294
Ind2  1   -0.400267
      2   -0.616860
      3   -0.685990
Ind3  1    0.027995
      2    0.337804
      3   -0.617471
dtype: float64

In [124]:
h_i_data.sum()

-1.9372670898483064

In [125]:
h_i_data.sum(level=1)

1   -0.061271
2   -0.396753
3   -0.620950
4   -0.858294
dtype: float64

In [126]:
h_i_data.sum(level=0)

Ind1    0.017522
Ind2   -1.703117
Ind3   -0.251672
dtype: float64

In [127]:
h_i_data

Ind1  1    0.311001
      2   -0.117696
      3    0.682512
      4   -0.858294
Ind2  1   -0.400267
      2   -0.616860
      3   -0.685990
Ind3  1    0.027995
      2    0.337804
      3   -0.617471
dtype: float64

**IO in pandas**

In this section, we will focus on I/O from text files, csv, excel, and sql files as well as getting data from web such as Yahoo! Finance. Using functions in pandas, you can read data as a DataFrame object. 

**Reading a csv file**

In [128]:
import pandas as pd
import numpy as np

In [129]:
roedatacsv = pd.read_csv('C://01 Projects//07 Personal_Projects//00 ISB Course//Python//Session 2//roedata.csv')
#roedatacsv
roedatacsv.head()

Industry Name  Number of firms     ROE
0        Advertising               65  16.51%
1  Aerospace/Defense               95  21.60%
2      Air Transport               25  42.68%
3            Apparel               70  17.87%
4       Auto & Truck               26  22.05%

If the file does not have a header, then you can either let pandas assign default headers or you can specify custom headers. If you want industry name to be the index of DataFrame, you can achieve that.

In [130]:
roedatacsv = pd.read_csv('C://01 Projects//07 Personal_Projects//00 ISB Course//Python//Session 2//roedata.csv', index_col = 'Industry Name' )
roedatacsv

Number of firms      ROE
Industry Name                                                
Advertising                                       65   16.51%
Aerospace/Defense                                 95   21.60%
Air Transport                                     25   42.68%
Apparel                                           70   17.87%
Auto & Truck                                      26   22.05%
Auto Parts                                        75   17.54%
Bank                                               7   15.03%
Banks (Regional)                                 721    9.52%
Beverage                                          47   27.62%
Beverage (Alcoholic)                              19   18.28%
Biotechnology                                    349    6.77%
Broadcasting                                      30   74.10%
Brokerage & Investment Banking                    49    9.25%
Building Materials                                37    6.78%
Business & Consumer Services                     179   12.48%
Cable TV                                          16   26.62%
Chemical (Basic)                                  47    8.80%
Chemical (Diversified)                            10   24.33%
Chemical (Specialty)                             100   22.10%
Coal & Related Energy                             45  -14.66%
Computer Services                                129   39.46%
Computer Software                                273   21.53%
Computers/Peripherals                             66   24.55%
Construction                                      18    3.62%
Diversified                                       20   13.06%
Educational Services                              40   -0.13%
Electrical Equipment                             135   13.67%
Electronics                                      191    7.98%
Electronics (Consumer & Office)                   26   25.66%
Engineering                                       56    7.61%
...                                              ...      ...
Railroad                                          10   19.85%
Real Estate (Development)                         22   -4.29%
Real Estate (General/Diversified)                 11    1.02%
Real Estate (Operations & Services)               47   19.84%
Recreation                                        70   18.03%
Reinsurance                                        3    6.05%
Restaurant                                        84   27.46%
Retail (Automotive)                               30   30.79%
Retail (Building Supply)                           7   23.12%
Retail (Distributors)                             87   12.92%
Retail (General)                                  21   17.68%
Retail (Grocery and Food)                         21   10.91%
Retail (Internet)                                 47   18.36%
Retail (Special Lines)                           137   17.29%
Rubber& Tires                                      4   45.41%
Semiconductor                                    104   13.14%
Semiconductor Equip                               51   -1.21%
Shipbuilding & Marine                             14    0.37%
Shoe                                              14   24.27%
Steel                                             37   -6.67%
Telecom (Wireless)                                28  -15.63%
Telecom. Equipment                               131   15.67%
Telecom. Services                                 82    5.78%
Thrift                                           223  -79.47%
Tobacco                                           12  214.71%
Transportation                                    22   14.75%
Trucking                                          28   16.01%
Utility (General)                                 20    7.34%
Utility (Water)                                   20    9.95%
Total Market                                    7766   15.68%

[97 rows x 2 columns]

In [131]:
roedatacsv = pd.read_csv('C://01 Projects//07 Personal_Projects//00 ISB Course//Python//Session 2//roedata.csv', usecols = ['Industry Name','ROE'] )
roedatacsv

Industry Name      ROE
0                           Advertising   16.51%
1                     Aerospace/Defense   21.60%
2                         Air Transport   42.68%
3                               Apparel   17.87%
4                          Auto & Truck   22.05%
5                            Auto Parts   17.54%
6                                  Bank   15.03%
7                      Banks (Regional)    9.52%
8                             Beverage    27.62%
9                  Beverage (Alcoholic)   18.28%
10                        Biotechnology    6.77%
11                         Broadcasting   74.10%
12       Brokerage & Investment Banking    9.25%
13                   Building Materials    6.78%
14         Business & Consumer Services   12.48%
15                             Cable TV   26.62%
16                     Chemical (Basic)    8.80%
17               Chemical (Diversified)   24.33%
18                 Chemical (Specialty)   22.10%
19                Coal & Related Energy  -14.66%
20                    Computer Services   39.46%
21                    Computer Software   21.53%
22                Computers/Peripherals   24.55%
23                         Construction    3.62%
24                          Diversified   13.06%
25                 Educational Services   -0.13%
26                 Electrical Equipment   13.67%
27                          Electronics    7.98%
28      Electronics (Consumer & Office)   25.66%
29                          Engineering    7.61%
..                                  ...      ...
67                             Railroad   19.85%
68            Real Estate (Development)   -4.29%
69    Real Estate (General/Diversified)    1.02%
70  Real Estate (Operations & Services)   19.84%
71                           Recreation   18.03%
72                          Reinsurance    6.05%
73                           Restaurant   27.46%
74                  Retail (Automotive)   30.79%
75             Retail (Building Supply)   23.12%
76                Retail (Distributors)   12.92%
77                     Retail (General)   17.68%
78            Retail (Grocery and Food)   10.91%
79                    Retail (Internet)   18.36%
80               Retail (Special Lines)   17.29%
81                        Rubber& Tires   45.41%
82                        Semiconductor   13.14%
83                  Semiconductor Equip   -1.21%
84                Shipbuilding & Marine    0.37%
85                                 Shoe   24.27%
86                                Steel   -6.67%
87                   Telecom (Wireless)  -15.63%
88                   Telecom. Equipment   15.67%
89                    Telecom. Services    5.78%
90                               Thrift  -79.47%
91                              Tobacco  214.71%
92                       Transportation   14.75%
93                             Trucking   16.01%
94                    Utility (General)    7.34%
95                      Utility (Water)    9.95%
96                         Total Market   15.68%

[97 rows x 2 columns]

In [135]:
capm_dem_data = pd.read_csv('C://01 Projects//07 Personal_Projects//00 ISB Course//Python//Session 2//capm_dem.dat', delimiter=' ',header = None)
capm_dem_data.head()

0       1         2         3
0  195710  880211 -0.012605  0.003871
1  195710  880212 -0.008511  0.007406
2  195710  880216  0.008584  0.001411
3  195710  880217 -0.004255  0.002414
4  195710  880218  0.000000  0.002845

In [139]:
capm_dem_data = pd.read_csv('C://01 Projects//07 Personal_Projects//00 ISB Course//Python//Session 2//capm_dem.dat', delimiter=' ',header = None)
capm_dem_data.head()

0       1         2         3
0  195710  880211 -0.012605  0.003871
1  195710  880212 -0.008511  0.007406
2  195710  880216  0.008584  0.001411
3  195710  880217 -0.004255  0.002414
4  195710  880218  0.000000  0.002845

In [141]:
compustatdata = pd.read_csv('C://01 Projects//07 Personal_Projects//00 ISB Course//Python//Session 2//compustat.csv', index_col = ['ggroup','gvkey'] )
compustatdata = compustatdata.sort_index(0,ascending=False)
compustatdata

datadate   fyear indfmt consol popsrc datafmt     tic  \
ggroup gvkey                                                           
5510.0 273902  20101231  2010.0   INDL      C      D     STD   PENGF   
       273902  20111231  2011.0   INDL      C      D     STD   PENGF   
       273902  20121231  2012.0   INDL      C      D     STD   PENGF   
       273902  20131231  2013.0   INDL      C      D     STD   PENGF   
       269005  20101231  2010.0   INDL      C      D     STD     CPL   
       269005  20111231  2011.0   INDL      C      D     STD     CPL   
       269005  20121231  2012.0   INDL      C      D     STD     CPL   
       269005  20131231  2013.0   INDL      C      D     STD     CPL   
       267054  20101231  2010.0   INDL      C      D     STD     EDN   
       267054  20111231  2011.0   INDL      C      D     STD     EDN   
       267054  20121231  2012.0   INDL      C      D     STD     EDN   
       267054  20131231  2013.0   INDL      C      D     STD     EDN   
       249448  20101231  2010.0   INDL      C      D     STD   IESFY   
       238616  20101231  2010.0   INDL      C      D     STD      VE   
       238616  20111231  2011.0   INDL      C      D     STD      VE   
       238616  20121231  2012.0   INDL      C      D     STD      VE   
       238616  20131231  2013.0   INDL      C      D     STD      VE   
       222357  20101231  2010.0   INDL      C      D     STD     CIG   
       222357  20111231  2011.0   INDL      C      D     STD     CIG   
       222357  20121231  2012.0   INDL      C      D     STD     CIG   
       222357  20131231  2013.0   INDL      C      D     STD     CIG   
       220942  20101231  2010.0   INDL      C      D     STD   GDFZY   
       220942  20111231  2011.0   INDL      C      D     STD   GDFZY   
       220942  20121231  2012.0   INDL      C      D     STD   GDFZY   
       220942  20131231  2013.0   INDL      C      D     STD   GDFZY   
       212950  20101231  2010.0   INDL      C      D     STD     PAM   
       212950  20111231  2011.0   INDL      C      D     STD     PAM   
       212950  20121231  2012.0   INDL      C      D     STD     PAM   
       212950  20131231  2013.0   INDL      C      D     STD     PAM   
       211819  20100331  2009.0   INDL      C      D     STD     NGG   
...                 ...     ...    ...    ...    ...     ...     ...   
NaN    5298    20121231  2012.0   INDL      C      D     STD  HEN.UN   
       5298    20131231  2013.0   INDL      C      D     STD  HEN.UN   
       5215    20101231  2010.0   INDL      C      D     STD    WTMK   
       5215    20111231  2011.0   INDL      C      D     STD    WTMK   
       5024    20101231  2010.0   INDL      C      D     STD     GAM   
       5024    20111231  2011.0   INDL      C      D     STD     GAM   
       5024    20121231  2012.0   INDL      C      D     STD     GAM   
       5024    20131231  2013.0   INDL      C      D     STD     GAM   
       4695    20100331  2009.0   INDL      C      D     STD    FCIC   
       4695    20110331  2010.0   INDL      C      D     STD    FCIC   
       4695    20120331  2011.0   INDL      C      D     STD    FCIC   
       4695    20130331  2012.0   INDL      C      D     STD    FCIC   
       4681    20111231  2011.0   INDL      C      D     STD    HPAC   
       4681    20121231  2012.0   INDL      C      D     STD    HPAC   
       4681    20131231  2013.0   INDL      C      D     STD    HPAC   
       3389    20101231  2010.0   INDL      C      D     STD     LGZ   
       3389    20111231  2011.0   INDL      C      D     STD     LGZ   
       1507    20121231  2012.0   INDL      C      D     STD    HYEM   
       1507    20131231  2013.0   INDL      C      D     STD    HYEM   
       1417    20100630  2010.0   INDL      C      D     STD     VBF   
       1417    20110630  2011.0   INDL      C      D     STD     VBF   
       1417    20120630  2012.0   INDL      C      D     STD     VBF   
       1417    20130630  2013.0   INDL      C      D   

In [142]:
crsp_data = pd.read_table('C://01 Projects//07 Personal_Projects//00 ISB Course//Python//Session 2//crsp.output', sep='\s+',header = None)
crsp_data

C:\08_Installations\anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


0         1         2         3         4     5       6      7   \
0    00036110  19840831  19890929  3.311923  22.62500  0.97   0.597 -0.172   
1    00036110  19850830  19900928  0.378167  22.62500  1.51   0.640 -0.028   
2    00036110  19860829  19910930  0.104652  23.50000  1.27   0.446  0.178   
3    00036110  19870831  19920930 -0.391107  37.37500  1.50   0.342  0.371   
4    00036110  19880831  19930930 -0.408846  24.62500  1.34   0.385  0.286   
5    00036110  19890831  19940930 -0.547627  34.62500  1.56   0.309  0.248   
6    00036110  19900831  19950929  0.002083  15.87500  1.60   0.743  0.185   
7    00036110  19910830  19960930  0.639713  16.25000  0.93   0.750  0.058   
8    00088610  19840131  19890228  0.928572  13.75000  0.95   0.464  0.176   
9    00088610  19850131  19900228  3.300000  13.25000  0.57   0.533 -0.017   
10   00088610  19860131  19910228  2.375000  22.50000  1.37   0.373  0.076   
11   00088610  19870130  19920228  0.884146  23.50000  1.39   0.298  0.206   
12   00088610  19880129  19930226  1.388489  17.25000  1.18   0.338  0.267   
13   00088610  19890131  19940228  5.226804  13.37500  1.30   0.533  0.302   
14   00088610  19900131  19950228  5.068027  17.50000  1.25   0.477  0.298   
15   00088610  19910131  19960229  5.489796  26.25000  1.73   0.384  0.177   
16   00095710  19840131  19890228  0.433400  23.25000  2.26   0.724  0.107   
17   00095710  19850131  19900228  0.835788  25.00000  2.12   0.683  0.081   
18   00095710  19860131  19910228  0.511377  22.12500  1.38   0.794 -0.012   
19   00095710  19870130  19920228  1.198015  23.75000  1.53   0.767 -0.066   
20   00095710  19880129  19930226  1.433394  20.00000  1.30   0.934 -0.113   
21   00103010  19860530  19910628 -0.556604  13.25000  1.01   1.023  0.524   
22   00103110  19910131  19960229  3.483710   7.75000  0.81   0.978  0.054   
23   00105510  19840330  19890428  4.260434  16.75000  1.70   0.776 -0.052   
24   00105510  19850329  19900430  1.102349  27.00000  2.72   0.510  0.098   
25   00105510  19860331  19910430  0.886910  38.16666  1.80   0.297  0.248   
26   00105510  19870331  19920430  1.204124  25.75000  1.96   0.431  0.314   
27   00105510  19880331  19930430  1.944473  16.25000  1.16   0.418  0.282   
28   00105510  19890331  19940429  1.653188  17.00000  1.35   0.466  0.235   
29   00105510  19900330  19950428  2.715672  14.75000  1.00   0.586  0.120   
..        ...       ...       ...       ...       ...   ...     ...    ...   
661  05527050  19870331  19920430  1.543598   8.56250  0.79  65.589  0.098   
662  05527050  19880331  19930430  1.775276   8.00000  1.00  84.524  0.130   
663  05527050  19890331  19940429  1.422740   9.81250  1.14  60.302  0.150   
664  05527050  19900330  19950428  0.833697  12.81250  1.24  53.617  0.153   
665  05527050  19910328  19960430  0.611784  12.12500  0.46  41.533 -0.009   
666  05534B10  19840330  19890428  0.750622  23.25000  2.78   0.853  0.062   
667  05534B10  19850329  19900430  0.632114  29.12500  3.05   0.703  0.087   
668  05534B10  19860331  19910430  0.805334  28.50000  3.02   0.757  0.104   
669  05534B10  19870331  19920430  0.621981  32.37500  2.78   0.707  0.033   
670  05534B10  19880331  19930430  0.572517  30.75000  3.01   0.829  0.025   
671  05534B10  19890331  19940429  0.570449  31.00000  2.59   0.876 -0.014   
672  05534B10  19900330  19950428  0.201547  35.12500  3.38   0.778  0.004   
673  05534B10  19910328  19960430  0.476158  36.00000  3.02   0.792  0.012   
674  05544210  19880429  19930528  6.724358   8.25000  0.47   0.662 -0.059   
675  05544210  19890428  19940531  2.073009  12.75000  1.02   0.355  0.088   
676  05544210  19900430  19950531  2.713574  14.50000  1.32   0.346  0.261   
677  05544210  19910430  19960531  1.302734  26.25000  1.64   0.165  0.353   
678  05560710  19840330  19890428 -0.472315  19.50000  1.66   0.778  0.105   
679  05560710  19880331  19930430  0.921570   6.37500  0.85   0.269 -0.111   
680  05560710  19890331  19940429

**Reading Files in Chunks**

When dealing with very large files, sometimes it is handy to work with a subset of file or to work on file iteratively in smaller chunks. This can be done in pandas using chunksize and nrows.

In [153]:
altdata = pd.read_csv('C://01 Projects//07 Personal_Projects//00 ISB Course//Python//Session 2//compustat.csv', chunksize=1000 )
altdata

In [154]:
#Try not to run this
altdata1 = pd.read_csv('C://01 Projects//07 Personal_Projects//00 ISB Course//Python//Session 2//compustat.csv')
altdata1.count()

gvkey       44289
datadate    44289
fyear       44220
indfmt      44289
consol      44289
popsrc      44289
datafmt     44289
tic         44288
conm        44289
curcd       44220
fyr         44220
act         28445
artfs           0
at          34434
ebitda      33277
epsfi       33007
ni          34255
costat      44289
ggroup      35214
dtype: int64

Note that in previous case, you did not receive a table as output. Instead you were given an object. This is called a TextParser object. This object allows you to iterate over the complete compustat file according to the chunksize you mentioned. Let us suppose we want to aggregate ebitda values of the entire dataset. 

In [179]:
total = 0
altdata
for chunks in altdata:
    total += chunks['ESTIMATOR'].sum()
    print(total)
total

TypeError: unsupported operand type(s) for +=: 'int' and 'str'

** Handling missing values**

Some types of missing values are automatically identified by pandas as NaN while importing the data. Those types are NA, NULL, -1.#IND. Additionally, you can also specify a list of missing values. 

In [160]:
roemissing = pd.read_csv('C://01 Projects//07 Personal_Projects//00 ISB Course//Python//Session 2//roemissing.csv', na_values=['NULL',-999] )
roemissing

Industry Name  Number of firms        ROE
0                           Advertising             65.0     16.51%
1                     Aerospace/Defense             95.0     21.60%
2                         Air Transport             25.0     42.68%
3                               Apparel             70.0     17.87%
4                          Auto & Truck             26.0     22.05%
5                            Auto Parts             75.0     17.54%
6                                  Bank              7.0     15.03%
7                      Banks (Regional)            721.0      9.52%
8                             Beverage              47.0     27.62%
9                  Beverage (Alcoholic)             19.0     18.28%
10                        Biotechnology            349.0      6.77%
11                         Broadcasting             30.0     74.10%
12       Brokerage & Investment Banking             49.0      9.25%
13                   Building Materials             37.0      6.78%
14         Business & Consumer Services              NaN     12.48%
15                             Cable TV             16.0     26.62%
16                     Chemical (Basic)             47.0  10000.00%
17               Chemical (Diversified)             10.0    145.00%
18                 Chemical (Specialty)            100.0     22.10%
19                Coal & Related Energy             45.0    -14.66%
20                    Computer Services            129.0     39.46%
21                    Computer Software            273.0     21.53%
22                Computers/Peripherals             66.0     24.55%
23                         Construction             18.0      3.62%
24                          Diversified             20.0     13.06%
25                 Educational Services             40.0     -0.13%
26                 Electrical Equipment            135.0     13.67%
27                          Electronics            191.0      7.98%
28      Electronics (Consumer & Office)             26.0     25.66%
29                          Engineering             56.0      7.61%
..                                  ...              ...        ...
67                             Railroad             10.0     19.85%
68            Real Estate (Development)             22.0     -4.29%
69    Real Estate (General/Diversified)             11.0      1.02%
70  Real Estate (Operations & Services)             47.0     19.84%
71                           Recreation             70.0     18.03%
72                          Reinsurance              3.0      6.05%
73                           Restaurant             84.0     27.46%
74                  Retail (Automotive)             30.0     30.79%
75             Retail (Building Supply)              7.0     23.12%
76                Retail (Distributors)             87.0     12.92%
77                     Retail (General)             21.0     17.68%
78            Retail (Grocery and Food)             21.0     10.91%
79                    Retail (Internet)             47.0     18.36%
80               Retail (Special Lines)            137.0     17.29%
81                        Rubber& Tires              4.0     45.41%
82                        Semiconductor            104.0     13.14%
83                  Semiconductor Equip             51.0     -1.21%
84                Shipbuilding & Marine             14.0      0.37%
85                                 Shoe             14.0     24.27%
86                                Steel             37.0     -6.67%
87                   Telecom (Wireless)             28.0    -15.63%
88                   Telecom. Equipment            131.0     15.67%
89                    Telecom. Services             82.0      5.78%
90                               Thrift            223.0    -79.47%
91                              Tobacco             12.0    214.71%
92                       Transportation             22.0     14.75%
93                             Trucking             28.0     16.01%
94            

In [161]:
roemissing = pd.read_csv('C://01 Projects//07 Personal_Projects//00 ISB Course//Python//Session 2//roemissing.csv', na_values={'Number of firms':['NULL',-999],'ROE':['10000.00%']} )
roemissing

Industry Name  Number of firms      ROE
0                           Advertising             65.0   16.51%
1                     Aerospace/Defense             95.0   21.60%
2                         Air Transport             25.0   42.68%
3                               Apparel             70.0   17.87%
4                          Auto & Truck             26.0   22.05%
5                            Auto Parts             75.0   17.54%
6                                  Bank              7.0   15.03%
7                      Banks (Regional)            721.0    9.52%
8                             Beverage              47.0   27.62%
9                  Beverage (Alcoholic)             19.0   18.28%
10                        Biotechnology            349.0    6.77%
11                         Broadcasting             30.0   74.10%
12       Brokerage & Investment Banking             49.0    9.25%
13                   Building Materials             37.0    6.78%
14         Business & Consumer Services              NaN   12.48%
15                             Cable TV             16.0   26.62%
16                     Chemical (Basic)             47.0      NaN
17               Chemical (Diversified)             10.0  145.00%
18                 Chemical (Specialty)            100.0   22.10%
19                Coal & Related Energy             45.0  -14.66%
20                    Computer Services            129.0   39.46%
21                    Computer Software            273.0   21.53%
22                Computers/Peripherals             66.0   24.55%
23                         Construction             18.0    3.62%
24                          Diversified             20.0   13.06%
25                 Educational Services             40.0   -0.13%
26                 Electrical Equipment            135.0   13.67%
27                          Electronics            191.0    7.98%
28      Electronics (Consumer & Office)             26.0   25.66%
29                          Engineering             56.0    7.61%
..                                  ...              ...      ...
67                             Railroad             10.0   19.85%
68            Real Estate (Development)             22.0   -4.29%
69    Real Estate (General/Diversified)             11.0    1.02%
70  Real Estate (Operations & Services)             47.0   19.84%
71                           Recreation             70.0   18.03%
72                          Reinsurance              3.0    6.05%
73                           Restaurant             84.0   27.46%
74                  Retail (Automotive)             30.0   30.79%
75             Retail (Building Supply)              7.0   23.12%
76                Retail (Distributors)             87.0   12.92%
77                     Retail (General)             21.0   17.68%
78            Retail (Grocery and Food)             21.0   10.91%
79                    Retail (Internet)             47.0   18.36%
80               Retail (Special Lines)            137.0   17.29%
81                        Rubber& Tires              4.0   45.41%
82                        Semiconductor            104.0   13.14%
83                  Semiconductor Equip             51.0   -1.21%
84                Shipbuilding & Marine             14.0    0.37%
85                                 Shoe             14.0   24.27%
86                                Steel             37.0   -6.67%
87                   Telecom (Wireless)             28.0  -15.63%
88                   Telecom. Equipment            131.0   15.67%
89                    Telecom. Services             82.0    5.78%
90                               Thrift            223.0  -79.47%
91                              Tobacco             12.0  214.71%
92                       Transportation             22.0   14.75%
93                             Trucking             28.0   16.01%
94                    Utility (General)             20.0    7.34%
95                      Utility (Water)             20.0    9.95%


**Writing Data**

In [162]:
roedata = pd.read_csv('C://01 Projects//07 Personal_Projects//00 ISB Course//Python//Session 2//roedata.csv')
roedata.to_csv('C://01 Projects//07 Personal_Projects//00 ISB Course//Python//Session 2//roedatawrite.csv')

In [165]:
roedata = pd.read_csv('C://01 Projects//07 Personal_Projects//00 ISB Course//Python//Session 2//roedata.csv')
roedata.to_csv('C://01 Projects//07 Personal_Projects//00 ISB Course//Python//Session 2//roedatawrite2.csv', index=False, col=['Industry Name','ROE'])

TypeError: to_csv() got an unexpected keyword argument 'col'

**Merging Data**

In [166]:
import pandas as pd

In [167]:
left_frame = pd.DataFrame({'key': range(5), 
                           'left_value': ['a', 'b', 'c', 'd', 'e']})
right_frame = pd.DataFrame({'key': range(2, 7), 
                           'right_value': ['f', 'g', 'h', 'i', 'j']})
print(left_frame)
print('\n')
print(right_frame)

   key left_value
0    0          a
1    1          b
2    2          c
3    3          d
4    4          e


   key right_value
0    2           f
1    3           g
2    4           h
3    5           i
4    6           j


In [168]:
pd.merge(left_frame, right_frame, on='key', how='inner')

key left_value right_value
0    2          c           f
1    3          d           g
2    4          e           h

In [169]:
pd.merge(left_frame, right_frame, on='key', how='left')

key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c           f
3    3          d           g
4    4          e           h

In [170]:
pd.merge(left_frame, right_frame, on='key', how='right')

key left_value right_value
0    2          c           f
1    3          d           g
2    4          e           h
3    5        NaN           i
4    6        NaN           j

In [171]:
pd.merge(left_frame, right_frame, on='key', how='outer')

key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c           f
3    3          d           g
4    4          e           h
5    5        NaN           i
6    6        NaN           j

In [178]:
pd.concat([left_frame, right_frame],sort=False)

key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c         NaN
3    3          d         NaN
4    4          e         NaN
0    2        NaN           f
1    3        NaN           g
2    4        NaN           h
3    5        NaN           i
4    6        NaN           j

In [173]:
pd.concat([left_frame, right_frame], axis=1)

key left_value  key right_value
0    0          a    2           f
1    1          b    3           g
2    2          c    4           h
3    3          d    5           i
4    4          e    6           j